version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lidar-api
      - lidar-ui
    ports:
      - 9000:7800

  lidar-api:
    build: lidar-api
    image: lidar-api
    restart: "no"
    volumes:
      - ./lidar-api/:/app
      - ./app-cache/:/app-cache
      - ./lidar-api/pointClouds/:/app/pointClouds
    expose:
      - 7777
    # depends_on:
    #   - database
    #   - flyway
    env_file:
      - project.env

  lidar-ui:
    build: lidar-ui
    image: lidar-ui
    restart: "no"
    volumes:
      - ./lidar-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - lidar-api

  database:
    container_name: lidar-database-server
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests